# Generated by Django 2.2 on 2021-04-17 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_proj_app', '0003_auto_20210417_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall_post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='solo_proj_app.User'),
        ),
    ]
