# Generated by Django 2.2 on 2021-04-19 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_proj_app', '0004_auto_20210417_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='solo_proj_app.User')),
                ('wall_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='solo_proj_app.Wall_Post')),
            ],
        ),
    ]
