# Generated by Django 2.2 on 2021-04-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_proj_app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall_post',
            name='users_like_wall_post',
            field=models.ManyToManyField(related_name='wall_post_liked', to='solo_proj_app.User'),
        ),
    ]
