# Generated by Django 2.2 on 2021-04-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_proj_app', '0006_wall_post_users_like_wall_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='users_like_comment',
            field=models.ManyToManyField(related_name='comment_liked', to='solo_proj_app.User'),
        ),
    ]
